- name: Install PostgreSQL
  apt:
    name: "postgresql-{{ postgres_version }}"
    state: present

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
    enabled: yes