- name: Set up replication user (on primary)
  when: inventory_hostname == "primary"
  become_user: postgres
  shell: |
    psql -c "CREATE ROLE {{ replication_user }} WITH REPLICATION PASSWORD '{{ replication_password }}' LOGIN;"

- name: Set up .pgpass file
  copy:
    src: pgpass
    dest: "{{ pgpass_file }}"
    owner: postgres
    group: postgres
    mode: '0600'

- name: Configure replication (on replicas)
  when: inventory_hostname != "primary"
  become_user: postgres
  shell: |
    rm -rf {{ postgres_data_dir }}/*
    pg_basebackup -h {{ primary_ip }} -D {{ postgres_data_dir }} -U {{ replication_user }} -Fp -Xs -P
  environment:
    PGPASSFILE: "{{ pgpass_file }}"

- name: Copy recovery configuration (on replicas)
  when: inventory_hostname != "primary"
  template:
    src: recovery.conf.j2
    dest: "{{ postgres_data_dir }}/recovery.conf"
    owner: postgres
    group: postgres
    mode: '0640'
  notify: restart postgresql