---

# PostgreSQL General Configuration
postgresql_version: 16
postgresql_service_name: postgresql

# PostgreSQL System User
postgres_user: postgres
postgres_group: postgres
replication_user: replica_user

# PostgreSQL Directory
postgre_primary_directory: /etc/postgresql/{{ postgresql_version }}/main
postgres_data_dir: /var/lib/postgresql/{{ postgresql_version }}/main

# Fetch primary server host dynamically
primary_ansible_host: "{{ hostvars.primary.ansible_host }}"

# Fetch replica ips for pg_hba.conf template
replica_ips: "{{ groups['replicas'] | map('extract', hostvars, 'ansible_host') | list }}"

