postgres_version: 14
postgres_data_dir: /var/lib/postgresql/{{ postgres_version }}/main

postgres_primary_user: "primary_user"
postgres_primary_password: "{{ vault_primary_user_password }}"

replication_user: replicator
replication_password: "{{ vault_replication_password }}"
primary_ip: <primary-private-ip>
pgpass_file: "/var/lib/postgresql/.pgpass"
